/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

type s = {
  schemaVersion: string;
  title: string;
  description: string;
  author: string;
  sourceLanguage: string;
  features: Array<{
    version: string;
    name: string;
    type: "TRANSLATION" | "PHONETICS" | "MORFOLOGY";
    max_rpm: number; // max requests per minute
    options: {
      // depends on type
    };
  }>;
  data: Array<string>;
};

export interface BankPrototypeSchema {
  schema_version: string;
  title: string;
  description: string;
  author: string;
  lang: string;
  modes: (ModeTranslate | ModeStress)[];
  /**
   * @minItems 1
   */
  data: [EnhancedDataItem, ...EnhancedDataItem[]];
}
export interface ModeTranslate {
  name: "translate";
  lang: string;
}
export interface ModeStress {
  name: "stresses";
}
export interface EnhancedDataItem {
  word: string;
  data?: {
    [k: string]: unknown;
  };
  [k: string]: {
    [k: string]: unknown;
  };
}
